version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: erp-postgres
    environment:
      POSTGRES_DB: erp_platform
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erp_user -d erp_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: erp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MailHog for development email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: erp-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: erp-api
    environment:
      DATABASE_URL: postgresql://erp_user:erp_password@postgres:5432/erp_platform
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      EMAIL__SMTP_HOST: mailhog
      EMAIL__SMTP_PORT: 1025
      EMAIL__SMTP_USERNAME: ""
      EMAIL__SMTP_PASSWORD: ""
      EMAIL__FROM_EMAIL: noreply@erp-platform.local
      EMAIL__FROM_NAME: ERP Platform
      RUST_LOG: debug
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    volumes:
      - ./apps/api:/app
      - cargo_cache:/usr/local/cargo/registry
    restart: unless-stopped

  # Web Frontend (React)
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: erp-web
    environment:
      VITE_API_URL: http://localhost:3000/api/v1
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - node_modules_cache:/app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  cargo_cache:
  node_modules_cache:
